### ISSUE TITLE
Once filter is enabled you can't disable it again.

### ISSUE THREAD

**Issue by MartijnKaijser** [phil65/skin.estuary#10]
![screenshot022](https://cloud.githubusercontent.com/assets/907436/19820645/86dea9d4-9d5a-11e6-9934-47d7aa592a73.png)

If this is a core issue i'll create trac ticket for this.

**Comment by phil65** [comment]
hmm it´s a custom estuary radiobutton (with <selected>Container.Filtered</selected> )
Perhaps I should revert it back to a regular button so users dont have the impression  that this button toggles by clickin on it.

**Comment by phil65** [comment]
converted to regular buttons.
