### ISSUE TITLE
EPG window has "options" while channels view has "settings"

### ISSUE THREAD

**Issue by MartijnKaijser** [phil65/skin.estuary#11]
![screenshot023](https://cloud.githubusercontent.com/assets/907436/19820909/cf02c53c-9d5b-11e6-9646-f6b621624ed1.png)
![screenshot024](https://cloud.githubusercontent.com/assets/907436/19820927/e3461ed6-9d5b-11e6-9149-b8b99f55985e.png)

**Comment by phil65** [comment]
not exactly sure what you mean?

**Comment by MartijnKaijser** [comment]
See the left bottom

**Comment by phil65** [comment]
yes, because itś a different button. ;) (menu)
