### ISSUE TITLE
Fresh install homescreen issues: inconsistent layout

### ISSUE THREAD

**Issue by MartijnKaijser** [phil65/skin.estuary#122]
Layout on homescreen is not consistent
![screenshot002](https://cloud.githubusercontent.com/assets/907436/20631607/d80a9050-b337-11e6-886b-69cfde0fce12.png)
![screenshot003](https://cloud.githubusercontent.com/assets/907436/20631609/d80c72e4-b337-11e6-8711-bcd7400cad9b.png)
![screenshot004](https://cloud.githubusercontent.com/assets/907436/20631610/d80d7e5a-b337-11e6-8b04-aad35113c7e9.png)
![screenshot005](https://cloud.githubusercontent.com/assets/907436/20631608/d80ab382-b337-11e6-8c06-15e0df062758.png)
![screenshot000](https://cloud.githubusercontent.com/assets/907436/20631606/d80a63dc-b337-11e6-8c97-dd6a52ea98eb.png)
![screenshot001](https://cloud.githubusercontent.com/assets/907436/20631605/d808a272-b337-11e6-9726-c5d8b7a62d7a.png)

**Comment by phil65** [comment]
should be fixed in my repo.

**Comment by phil65** [comment]
...that empty screen for pictures is a core issue btw. Sometimes I get the "picture add-ons" entry shown there, sometimes not.
