### ISSUE TITLE
better fade in-effect for fanarts

### ISSUE THREAD

**Issue by Ston3s** [phil65/skin.estuary#147]
The next gen Estuary looks great!
I have only small suggestions to improve the look.

In kodi17 beta6 the fanarts moving from the right side into the screen if you change the categories of the  main-menu (Movies/TV Shows/Music/Music Videos...)
Maybe its possible that the fanart comes not from the right side but fading in/fading over the fanart/picture that before displayed.

Sorry for my english and hope you understand me :)

**Comment by phil65** [comment]
removed the bgs, should be fine now.
