### ISSUE TITLE
idea: only show the "options" text next to cogwheel for limited time

### ISSUE THREAD

**Issue by MartijnKaijser** [phil65/skin.estuary#15]
Current the "options" text is continuously shown next to the arrow/cogwheel. Perhaps just show it for several seconds while entering a windows (or whatever) and then hide the text and keep the arrow/cogwheel.
I'm sure users will learn what the icon means and then text because superfluous. Just a thought

**Comment by phil65** [comment]
Tried it, but wasnt totally convinced. Will close for now since this isnt really a bug.
