### ISSUE TITLE
hide watched option is gone from side panel in library

### ISSUE THREAD

**Issue by MartijnKaijser** [phil65/skin.estuary#150]

**Comment by graysky2** [comment]
http://forum.kodi.tv/showthread.php?tid=298573

**Comment by phil65** [comment]
doesnt happen here. Debug log / screenshots or I will consider this garbage. ;)

**Comment by phil65** [comment]
![screenshot025](https://cloud.githubusercontent.com/assets/110931/20859498/4e7f841e-b961-11e6-96ed-4e4f7f90b5b5.png)

**Comment by MartijnKaijser** [comment]
right...
