### ISSUE TITLE
options button is missing to bring up side panel

### ISSUE THREAD

**Issue by MartijnKaijser** [phil65/skin.estuary#151]
![screenshot000](https://cloud.githubusercontent.com/assets/907436/20858892/9c2431cc-b94f-11e6-8fc5-61a01db78e72.png)
![screenshot001](https://cloud.githubusercontent.com/assets/907436/20858899/9f69903e-b94f-11e6-9141-8f89f93e5d22.png)

**Comment by phil65** [comment]
Thx!

**Comment by phil65** [comment]
fixed.
