### ISSUE TITLE
Full Screen Music

### ISSUE THREAD

**Issue by jjd-uk** [phil65/skin.estuary#189]
With Estuary they is no way to display only the Visualisation with no other GUI items, when you enter Full Screen Music you see:

![screenshot000](https://cloud.githubusercontent.com/assets/5781142/21565798/fd5babec-ce93-11e6-9ce0-b338c4558022.png)

This always stays on screen until you press I to dismiss the on screen info, however you are still left with:

![screenshot001](https://cloud.githubusercontent.com/assets/5781142/21565808/13fa0448-ce94-11e6-93b3-b9b6da2e206b.png)

For me when in Full Screen Music with Visualisation enabled then it's the Visualisation I want to be the major focus, so I want to be able to have nothing getting in the way of it.

Confluence had a good balance where entering Full Screen in Confluence would give:

![screenshot003](https://cloud.githubusercontent.com/assets/5781142/21565838/670bcb76-ce94-11e6-9cea-ceff0b778f2e.png)

With no input from user after 10 seconds the info would auto disappear leaving:

![screenshot004](https://cloud.githubusercontent.com/assets/5781142/21565850/87f25a6c-ce94-11e6-9c24-feac0f6d63c6.png)

Giving the Visualisation full focus with nothing blocking/getting in the way of it. The info would only then reappear for 10 seconds on each track change. If the user always wanted the Info on screen they could press I to show the info (with no time out in this case) then press I again to hide when no longer wanted.

**Comment by jjd-uk** [comment]
Just noticed this https://github.com/phil65/skin.estuary/pull/164 would I guess would remove that bottom time line.

IMHO the Now Playing top left and Time top right items should go also.

**Comment by host505** [comment]
Check out my approach:
https://github.com/phil65/skin.estuary/pull/164#issuecomment-269888745
Not sure if I should make a new pr.
