### ISSUE TITLE
Log shows genre image errors when navigating home screen

### ISSUE THREAD

**Issue by MartijnKaijser** [phil65/skin.estuary#19]
I don't have this genre pack installed
`08:16:28 T:139043247168   ERROR: DoWork - Direct texture file loading failed for resource://resource.images.moviegenreicons.transparent/Romance.png
08:16:28 T:139043247168   DEBUG: GetImageHash - unable to stat url resource://resource.images.moviegenreicons.transparent/Romance.png
08:16:28 T:139043247168   ERROR: DoWork - Direct texture file loading failed for resource://resource.images.moviegenreicons.transparent/Animation.png
08:16:28 T:139043247168   DEBUG: GetImageHash - unable to stat url resource://resource.images.moviegenreicons.transparent/Animation.png
08:16:28 T:139043247168   ERROR: DoWork - Direct texture file loading failed for resource://resource.images.moviegenreicons.transparent/Family.png
08:16:28 T:139043247168   DEBUG: GetImageHash - unable to stat url resource://resource.images.moviegenreicons.transparent/Family.png
08:16:28 T:139043247168   ERROR: DoWork - Direct texture file loading failed for resource://resource.images.moviegenreicons.transparent/Comedy.png
08:16:28 T:139043247168   DEBUG: GetImageHash - unable to stat url resource://resource.images.moviegenreicons.transparent/Comedy.png
08:16:28 T:139043247168   ERROR: DoWork - Direct texture file loading failed for resource://resource.images.moviegenreicons.transparent/Adventure.png
08:16:28 T:139043247168   DEBUG: GetImageHash - unable to stat url resource://resource.images.moviegenreicons.transparent/Adventure.png
08:16:28 T:139043247168   ERROR: DoWork - Direct texture file loading failed for resource://resource.images.moviegenreicons.transparent/Science Fiction.png
08:16:28 T:139043247168   DEBUG: GetImageHash - unable to stat url resource://resource.images.moviegenreicons.transparent/Science Fiction.png
08:16:28 T:138660537408   DEBUG: RunQuery took 31 ms for 25 items query: SELECT * FROM tvshow_view  WHERE watchedCount != 0 AND totalCount != watchedCount ORDER BY c00`

**Comment by phil65** [comment]
fixed.
