### ISSUE TITLE
No Ratings?

### ISSUE THREAD

**Issue by da3dsoul** [phil65/skin.estuary#192]
I found it odd that User Ratings were the only Ratings included, and only in very select places.
This is what I have in my edit, but I'm not positive it works in all circumstances.
![screenie](https://dl.dropboxusercontent.com/u/31454410/Github%20Issues/screenshot003%20(1).png)

**Comment by Jielde** [comment]
+1 :)

**Comment by JimmyS83** [comment]
+1

**Comment by zag2me** [comment]
Yep agreed, this is sorely missed by myself too.

**Comment by phil65** [comment]
available as skin setting in leia.

**Comment by da3dsoul** [comment]
Hehe. Did you use my icons?

**Comment by phil65** [comment]
Which icons do you mean?

**Comment by da3dsoul** [comment]
I made a thread on the forums with a bunch of variations of star rating icons. Guess no is the answer
