### ISSUE TITLE
Spinning disc on Addons > Program add-ons

### ISSUE THREAD

**Issue by MilhouseVH** [phil65/skin.estuary#196]
There's a spinning disc visible underneath the first "Program add-ons" icon in the Add-ons menu.  You'll only see the spinning disc when the first icon is a) not selected and b) the icon is transparent.

1) Start Kodi
2) Navigate down to Add-ons
3) View the spinning disc (if the first Program Add-ons icon is transparent)

Video: https://www.dropbox.com/s/e9zjeipq0kj5ukj/VID_20170114_224423.mp4?dl=0

If the first icon is selected or the icon is opaque so that you can't see the spinning disc, the disc may still be spinning as evidenced by the increased CPU load and temperature.

If I navigate to Settings (back up the Home menu, clicking on the cogged wheel), then exit back to the Home menu and navigate back down to Add-ons, the spinning disc is no longer visible, nor does it cause increased CPU load/temperature, so it appears the spinning disc is disabled after accessing Settings - maybe an uninitialized boolean/condition?

On low powered devices this spinning disc increases CPU/GPU load considerably. On an RPi3, although it only increases CPU load from an idle average of ~2.5% to ~8%, it does increase the SOC temperature considerably up to about 72C from 54C, while the system is otherwise idle. On an RPi it might max out the single CPU core. As soon as I switch away from the Add-ons menu the system load and temperature return to normal.

**Comment by phil65** [comment]
Did you check latest master? (perhaps this here fixes it: https://github.com/phil65/skin.estuary/commit/d100d3df70d14ad2db0609070ea92885378d85d7 )

**Comment by MilhouseVH** [comment]
Thanks, https://github.com/phil65/skin.estuary/commit/5afc534b6ea87fcc01e4a78bc76a40151a27f766 fixes it. :)
