### ISSUE TITLE
Log error when watching livetv and pulling up the nav bar

### ISSUE THREAD

**Issue by MartijnKaijser** [phil65/skin.estuary#20]
09:10:54 T:138579477568   DEBUG: ------ Window Init (DialogSeekBar.xml) ------
09:10:54 T:138579477568   DEBUG: Window DialogSeekBar.xml was already loaded
09:10:54 T:138579477568   DEBUG: Alloc resources: 0.01ms
09:10:54 T:138579477568   ERROR: CGUITextureManager::GetTexturePath: could not find texture 'flags/starrating/.png'
09:10:54 T:138579477568   DEBUG: ------ Window Init (Custom_1109_TopBarOverlay.xml) ------

**Comment by phil65** [comment]
fixed.
