### ISSUE TITLE
Some ideas...

### ISSUE THREAD

**Issue by myraspxbmc** [phil65/skin.estuary#200]
Hi phil65, when you have time can you please see this videos:
Iris - NOS        http://static1.nos.pt/iris/video/features/806x454_recomendacoes.mp4
Iris - NOS	http://static1.nos.pt/iris/video/features/806x454_gravacao_auto.mp4
Iris - NOS	http://static1.nos.pt/iris/video/features/806x454_iris_online.mp4
Iris - NOS	http://static1.nos.pt/iris/video/features/806x454_gravacao_avancada.mp4
Iris - NOS	http://static1.nos.pt/iris/video/features/806x454_restart.mp4
Iris - NOS	http://static1.nos.pt/iris/video/features/806x454_personalizacao.mp4
Iris - NOS	http://static1.nos.pt/iris/video/features/806x454_videoclube.mp4
I hope you like it...
Cheers

**Comment by phil65** [comment]
took a look, thx.
