### ISSUE TITLE
3D tag not working.

### ISSUE THREAD

**Issue by 3DBuff** [phil65/skin.estuary#211]
Any chance of bringing the 3D tag back? It disappeared with version 2 of Estuary skin quite some time ago. I used to get 3D tag beside movie poster out of filename "... .3D.MVC.iso". The tag is gone and unless I play the movie the system will not update any tags from .iso file itself or filename.

**Comment by phil65** [comment]
I am not really a fan of parsing the filename in order to show correct mediaflags (although i dont care too much in this case)
@ronie your opinion?

**Comment by ronie** [comment]
i'd say it's up to kodi to properly fill the stereoscopic infolabels/bools and it shouldn't be up to the skin to mask any shortcomings in kodi.

most likely, the 3d flag isn't the only flag missing for .iso files.

**Comment by 3DBuff** [comment]
The tags are populated once the movie is played.

If the movie library is scanned into database first time (or new movie added to library) the ISO file is not internally tested for video, audio tags etc. The title is taken from the file name and movie info populated from selected scraper. 2 ISO files of the same movie one 3D and the other 2D will look identical until played  to extract the rest of the internal data.

Having Video filenames flags will automatically add "3D" under movie poster before movie is played.
Filename flags are described here: http://kodi.wiki/view/3D
" .3D.MVC.ISO" should be added there as it used to work in initial release of Estuary skin in Raspberry version.

**Comment by phil65** [comment]
Since core already seems to check filenames, we shouldnt also do this on skinning level.
Proper fix would be that kodi tells skin properly that movie is 3d.
