### ISSUE TITLE
Allow to trim the available options in the 'Power' button

### ISSUE THREAD

**Issue by elrodro83** [phil65/skin.estuary#213]
On some skins, it is allowed to remove some options from the power button (for instance, Exit).

This is needed to avoid accidentally getting to a state that is unrecoverable short of a hard reset or ssh'ing to the machine to reenter kodi or rebooting.

Many kodi installs have no keyboard or mouse, so there is no way to get past the login screen that appears when exiting kodi.

**Comment by phil65** [comment]
Sorry, this probably wont be done since we want to keep estuary as simple as possible, without settings for every menu.

**Comment by elrodro83** [comment]
Not even through config files? I Don't think a configuration option in the ui would be required for this.

**Comment by phil65** [comment]
you can always edit the xml files yourself if you want more customization.
