### ISSUE TITLE
Show "last played" in video information

### ISSUE THREAD

**Issue by Programie** [phil65/skin.estuary#228]
It would be nice if this skin shows when I watched a specific movie or TV show for the last time in the video information dialog (the one which shows the plot, rating, file location, actors, etc).

I've used the Aeon Nox skin before upgrading to Kodi 17 "Krypton" which has such a feature. But today, I like the Estuary skin much more and therefore I'm missing this feature. 🙂

**Comment by phil65** [comment]
https://github.com/phil65/skin.estuary/commit/66ca5ae513d9b195e2436bde20ddff2c7d572cb3
