### ISSUE TITLE
Media sources on Videos screen do not respect <lockmode>

### ISSUE THREAD

**Issue by josephfh** [phil65/skin.estuary#239]
Items in the row of Media sources on the *Videos* screen do not respect the `<lockmode>1</lockmode>` setting in sources.xml

To replicate, add a numeric lock to a media source. It prompts for the password when accessed through the file browser (Videos -> Files -> ) but does not on the *Videos* screen.

**Comment by phil65** [comment]
This is not skin-related. Please report this issue on the forums.
