### ISSUE TITLE
EPG Guide Item will show an extraneous : if no episodetitle is provided

### ISSUE THREAD

**Issue by fuzzard** [phil65/skin.estuary#246]
Ive been working on the pvr.hdhomerun addon for a little while, and ive come across a display issue in regards to an EPG item from the Guide. 

If a series/episode number is provided to the EPG tag, and an episode title is not, an trailing : is shown when looking at the EPG entry. When an episode title is given, with no series/ep number, it works properly. This combination of data can be provided by SiliconDust's epg guide on a fairly regular basis, hence why ive noticed it.

The best way i can explain this was to alter the pvr.demo addon. Ive created a PR to it that can show the issue across the first 4 EPG entries. If you load the pvr.demo (with the PR applied), go into the Guide, and then open "Demo EPG Entry 4" it will show just the issue i talk about. Demo Entry 1-3 show other combinations of the 3 fields, all which are correctly displayed.

https://github.com/kodi-pvr/pvr.demo/pull/56

I believe the issue resides in the following location
https://github.com/xbmc/xbmc/blob/master/addons/skin.estuary/xml/DialogPVRInfo.xml
at line 122
`<param name="sub_label" value="$INFO[ListItem.Season, [COLOR grey]S[/COLOR]]$INFO[ListItem.Episode, [COLOR grey]E[/COLOR],: ]$INFO[ListItem.EpisodeName,[B],[/B]]" />
				<param name="posy" value="40" />`

Im not sure if the logic required to do this is available to the skinning side or not, just thought id ask about it. If you require any further details, please let me know.

**Comment by ksooo** [comment]
Fixed in xbmc master: https://github.com/xbmc/xbmc/pull/13158

**Comment by fuzzard** [comment]
Cheers, ill check it out.
