### ISSUE TITLE
Watched Overlay Needs Contrasting outline

### ISSUE THREAD

**Issue by benyjr** [phil65/skin.estuary#256]
The Watched Overlay (and probably many others) would benefit from an outline of a contrasting colour so it can be seen when it appears on a white background.  Otherwise it practically disappears.

**Comment by dagwieers** [comment]
[I learned yesterday](https://github.com/phil65/skin.estuary/issues/259#issuecomment-504913262) that this repository is unmaintained and you need to report issues at the upstream https://github.com/xbmc/xbmc repository. Good luck !

**Comment by benyjr** [comment]
This now exists in modern Kodi.
